### ISSUE TITLE
자유게시판 파일(이미지) 업로드

### ISSUE THREAD

**Issue by hellouz818** [Spring-Of-Reaction/OmyeoGamyeo#5]
자유게시판에서 파일업로드하는 부분에서 

이미지를 업로드 하면 그 이미지를 글에서 불러와서 업로드한 이미지가 작성한 글과 같이 보여지는건지 (ex, 에브리타임 게시글에서 이미지 업로드),
아님 이미지를 포함한 모든 파일을 업로드할 수 있도록 하여(jpg외에도 pdf, txt, csv, cpp등 모든 확장자 파일) 이미지는 뜨지 않고 첨부파일만 보여져서 그 파일을 눌렀을 경우 다운로드 될 수 있도록 하는 것인지 (ex, 스노로즈 족보),
아니면 위의 두 방법을 혼용하여 이미지는 보여지게하고 파일은 따로 저장할 수 있도록 해야하는것인지

프로토타입은 2번과 같은형식으로 만든거 같으나, 회의시에 1번으로 얘기한거 같아서 궁금하여 남깁니다. 의견 부탁드려요~!

**Comment by JIAH-LEA** [comment]
음 저는 1번과 같은 방법이라고 생각했어요! 
파일선택(이미지)>이미지 게시글에 보여지게하는 것으로요 저도 이미지 첨부에 대한 기능 구현은 처음이라 잘은 모르지만, 이미지 도메인을 따로 만들어서 컨트롤러랑 서비스 만들고 이미지의 아이디값과 이미지url을 저장하는 식으로 하면 되지 않을까 생각됩니다..!

**Comment by Heejingss** [comment]
저도 1번이라고 생각했습니다! 프로토타입에는 조금 부족하게 보여지는것 같은데, 에브리타임 게시글처럼 이미지와 게시글이 보이는 것이 좋을 것 같습니다~~!!
