### ISSUE TITLE
수정하기 빌더 패턴(@Builder())사용 관련

### ISSUE THREAD

**Issue by hellouz818** [Spring-Of-Reaction/OmyeoGamyeo#6]
수정하기에서 Post와 Review모두 Dto에서 update시 builder()를 사용하였는데 테스트진행시에 builder()에 명시한 항목 모두를 수정하지 않는다면 오류가 나는 상황이 발생했습니다.
검색해보니, builder()를 사용할때는 어떤 필드에 어떤값을 채울지 명시하는 역할이며,이 때 최대한 값을 바꾸지 않는것이 좋다고합니다.
그렇다면, 만약 builder()를 수정할때 사용한다면 받는 인자값의 갯수에 따라 고려해야하는 경우의 수가 많이 늘어날 것이라고 예상됩니다. 
(예를 들어, Post의 경우 title, content, category, filename, filepath가 추후 변경될 가능성이 있다고 생각되었는데 이에 해당하는 경우의 수를 모두 고려한다면 5+5C2+5C3+5C4+5C5 = 31개의 생성자를 생성해야한다고 느꼈습니다.)
그래서 builder()가 아닌 다른 방식으로 수정하기를 작성하는 것이 어떨지 의견을 묻고자 남깁니다.

혹시 잘못 생각하고 있는 부분이 있다면 알려주세요. 감사합니다!

참고한 블로그입니다. [https://lemontia.tistory.com/890]

**Comment by JIAH-LEA** [comment]
혹시 어떤 테스트코드를 작성했을 때 어떤 에러가 났는지 알 수 있을까요?

**Comment by hellouz818** [comment]
프론트 로컬스토리지에 저장하여 기존에 작성한 내용까지 한꺼번에 보내어 공백이 없을 수 있다는 것 확인했습니다! 감사합니다😀
